Buttons
js-tasks-ru/htmlcss-20230227_geo-alpha-contact pull request #4
Opened 2023-03-08 17:45 UTC by ageo-tl

2023-03-09 13:19 UTC, GSemikozov requested changes

2023-03-09 13:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 182px;
ширину не нужно ограничивать, достаточно чтобы она определялась внутренним содержимым

2023-03-09 13:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
и чтобы пользователь не мог нажать - pointer-events: none

2023-03-09 13:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-primary {
модификаторы - через 1 нижнее подчеркивание

2023-03-09 13:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
если транзишн общий - то лучше сразу на класс блока

2023-03-09 13:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
такой курсор будет по умолчанию у блока всегда

2023-03-09 16:21 UTC, ageo-tl commented
По замечаниям все исправлено

2023-03-10 08:55 UTC, GSemikozov requested changes

2023-03-10 08:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px 65px;
здесь еще один важный момент - чтобы высота была как в макете, надо указать `padding: 15px 65px 14px`

2023-03-10 16:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-10 17:11 UTC, GSemikozov approved these changes

2023-03-10 17:11 UTC, merged