Cards in content block by inline blocks and wrappers
js-tasks-ru/htmlcss-20230227_geo-alpha-contact pull request #9
Opened 2023-03-19 13:32 UTC by ageo-tl

2023-03-19 13:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-20 10:00 UTC, GSemikozov requested changes

2023-03-20 10:00 UTC, GSemikozov commented on components/button/button.css
> +.button {
а у нас ведь уже есть компонент Кнопка, зачем создавать еще один? удалим и будем использовать то что уже есть)

2023-03-20 10:00 UTC, GSemikozov commented on components/card/card.css
> +  height: 100%;
лишнее

2023-03-20 10:00 UTC, GSemikozov commented on components/content/content.css
> +  margin: 0 -15px;
чтобы этого не делать, можно использовать flex + gap

2023-03-20 10:00 UTC, GSemikozov commented on components/content/content.css
> +  padding: 15px;
паддинг и font-size - это внутренние свойства самой карточки

2023-03-20 16:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-22 10:49 UTC, GSemikozov requested changes

2023-03-22 10:49 UTC, GSemikozov commented on components/button/button.css
> +.button {
кнопки у нас уже есть и подключать их надо из `../../03-lection1/01-button/button.css`

2023-03-22 10:49 UTC, GSemikozov commented on components/content/content.css
> +  margin: 0 -15px;
повторюсь что отрицательные марджины не нужно использовать

2023-03-22 10:49 UTC, GSemikozov commented on components/content/content.css
> +  padding: 15px;
паддинги - часть блока card, а не элемента .content__card

2023-03-24 17:46 UTC, closed without merging